[alias]
lint-clippy = "clippy --workspace --all-targets -- -D warnings"
lint-fmt = "fmt --all -- --check"
fix-clippy = "clippy --workspace --all-targets --fix --allow-dirty --allow-staged -- -D warnings"
fix-fmt = "fmt --all"
